src/Codecool.CodecoolShop/Controllers/AuthenticationController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Codecool.CodecoolShop.Daos.Implementations.Database;
using Codecool.CodecoolShop.Helpers;
using Codecool.CodecoolShop.Models;
using Codecool.CodecoolShop.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Codecool.CodecoolShop.Controllers
{
    public class AuthenticationController : BaseController
    {
        public UserService UserService { get; set; }
        private CartService _cartService { get; set; }
        private readonly ILogger<ProductController> _logger;

        public AuthenticationController(ILogger<ProductController> logger, UserDaoDatabase userDao, CartDaoDatabase cartDao)
        {
            UserService = new UserService(userDao);
            _logger = logger;
            _cartService = new CartService(cartDao);
        }

        public IActionResult Register()
        {
            return View("RegisterIndex");
        }

        [HttpPost]
        public IActionResult Register(RegisterVM register)
        {
            if (!ModelState.IsValid) return View("RegisterIndex");

            AppUser newUser = new() { Email = register.Email, Password = register.Password };

            if (UserService.UserExists(register.Email))
            {
                ModelState.AddModelError(nameof(register.Email), "User already exists");
                return View("RegisterIndex");
            }

            UserService.AddNewUser(newUser);
            return RedirectToAction("Login");
        }

        public IActionResult Login()
        {
            return View("SignInIndex");
        }
        
        public IActionResult Logout()
        {
            SessionHelper.DeleteUserFromSession(HttpContext.Session, "user");
            return RedirectToAction("Index", "Product");
        }
        
        [HttpPost]
        public IActionResult Login(SingInVM signIn)
        {
            if (!ModelState.IsValid) return View("SignInIndex");

            AppUser user = new() { Email = signIn.Email, Password = signIn.Password };

            if (!UserService.UserExists(signIn.Email))
            {
                ModelState.AddModelError(nameof(signIn.Email), "You should consider registering...");
                return View("SignInIndex");
            }

            if (!UserService.ValidatePassword(signIn.Email, signIn.Password))
            {
                ModelState.AddModelError(nameof(signIn.Password), "Nice try, you hacker!");
                return View("SignInIndex");
            }

            SessionHelper.SetUserAsJson(HttpContext.Session, "user", signIn.Email);

            // check if user already has a cart saved
            List<ItemModel> cartDb = _cartService.GetCartForUser(signIn.Email);

            // associate already existing cart with the new user
            var cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
            if (cart != null)
            {
                cart.ForEach(x => x.AppUserEmail = signIn.Email);
                cart.AddRange(cartDb);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cartDb);
            }

            return RedirectToAction("Index", "Product");
        }
    }
}

src/Codecool.CodecoolShop/Controllers/CartController.cs
using System;
using Codecool.CodecoolShop.Helpers;
using Codecool.CodecoolShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Codecool.CodecoolShop.Daos;

namespace Codecool.CodecoolShop.Controllers
{
    public class CartController : BaseController
    {
        private readonly IProductDao _productDao;
        public CartController(IProductDao productDao)
        {
            _productDao = productDao;
        }

        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<ItemModel>();
            }

            CartModel cartModel = new CartModel { Items = cart, TotalPrice = cart.Sum(x => x.Product.DefaultPrice * x.Quantity) };

            return View(cartModel);
        }

        public JsonResult Buy(int id)
        {
            // move to service
            Product product = _productDao.Get(id);
            string userEmail = SessionHelper.GetUserFromJson(HttpContext.Session, "user");

            if (SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart") == null)
            {
                List<ItemModel> cart = new List<ItemModel>();
                cart.Add(new ItemModel { AppUserEmail = userEmail, ProductId = product.Id, Product = product, Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                return Json(cart);
            }
            else
            {
                List<ItemModel> cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
                int index = getIndexOfProduct(id, cart);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new ItemModel { AppUserEmail = userEmail, ProductId = product.Id, Product = product, Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                return Json(cart);
            }
        }

        public JsonResult Remove(int id)
        {
            List<ItemModel> cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
            int index = getIndexOfProduct(id, cart);
            if (cart[index].Quantity > 1)
            {
                cart[index].Quantity--;
            }
            else
            {
                cart.RemoveAt(index);
            }

            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);

            return Json(cart);
        }

        public JsonResult CartPreview()
        {
            List<ItemModel> cart;
            try
            {
                cart = SessionHelper.GetObjectFromJson<List<ItemModel>>(HttpContext.Session, "cart");
                ViewBag.cart = cart;
            }
            catch (ArgumentNullException)
            {
                cart = new List<ItemModel>();
            }

            return Json(cart);
        }

        private int getIndexOfProduct(int id, List<ItemModel> cart)
        {
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

src/Codecool.CodecoolShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Codecool.CodecoolShop.Daos;
using Codecool.CodecoolShop.Daos.Implementations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Codecool.CodecoolShop.Models;
using Codecool.CodecoolShop.Services;
using Codecool.CodecoolShop.DAL;

namespace Codecool.CodecoolShop.Controllers
{
    public class ProductController : BaseController
    {
        private readonly ILogger<ProductController> _logger;
        public ProductService ProductService { get; set; }

        public ProductController(ILogger<ProductController> logger, IProductDao productDao, IProductCategoryDao categoryDao, ISupplierDao supplierDao)
        {
            _logger = logger;

            ProductService = new ProductService(productDao, categoryDao, supplierDao);
        }

        public IActionResult Index()
        {
            _logger.LogInformation("Requested Index page");

            IEnumerable<Product> displayProducts = ProductService.GetProductsForCategory(0);

            IEnumerable<ProductCategory> categories = ProductService.GetAllCategories();
            IEnumerable<Supplier> suppliers = ProductService.GetAllSuppliers();
            var homePageModel = new HomePageModel
            {
                Categories = categories.ToList(),
                Products = displayProducts.ToList(),
                Suppliers = suppliers.ToList(),
                CategoryId = 0,
                SupplierId = 0
            };

            return View(homePageModel);
        }

        public ActionResult FilteredProducts(int categoryId, int supplierId)
        {
            IEnumerable<Product> productsInCategory = ProductService.GetProductsForCategory(categoryId);
            IEnumerable<Product> productsBySupplier = ProductService.GetProductsForSupplier(supplierId);

            IEnumerable<Product> displayProducts = productsInCategory.Where(x => productsBySupplier.Contains(x));

            //UPDATE HOMEPAGE STATE
            return PartialView("_PartialIndex", displayProducts.ToList());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Codecool.CodecoolShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Codecool.CodecoolShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/c3b1840293.js" crossorigin="anonymous"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">Codecool.CodecoolShop</a>
                <button class="navbar-toggler" type="button" Data-toggle="collapse" Data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div id="cart" class="cart" Data-closed="true">
                <i class="fa-solid fa-cart-plus" style="font-size: 18px"></i>
                <div id="cartContainer" class="cart-container">
                    <table>
                        <thead>
                        <tr>
                            <td>Image</td>
                            <td>Name</td>
                            <td>Price</td>
                            <td>Total<br />Price</td>
                        </tr>
                        </thead>
                        <tbody></tbody>
                        <tfoot>
                        <tr>
                            <td>
                                <a id="cartLink" href="@Url.Action("Index", "Cart")">See Cart...</a>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            @if (ViewData["user"] != null)
            {
                <a asp-controller="Authentication" asp-action="Logout" role="button" id="logOutBtn" class="mr-3 btn btn-primary ">Logout</a>
                <div class="px-3 py-2 bg-success text-light rounded" style="margin-right: 80px">
                    <p class="mb-0 text-nowrap">Welcome @ViewData["user"]</p>
                </div>
            }
            else
            {
                <div id="authenticationBtns" class="d-flex flex-row text-nowrap" style="margin-right: @(ViewData["user"] == null ? "80px" : "20px")">
                    <a asp-controller="Authentication" asp-action="Login" role="button" id="logInBtn" class="mr-3 btn btn-primary ">Log In</a>
                    <a asp-controller="Authentication" asp-action="Register" role="button" id="registerBtn" class="mr-3 btn btn-primary">Register</a>
                </div>
            }
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div id="modalBackground" class="modal-background"></div>
<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Codecool.CodecoolShop - <a asp-area="" asp-controller="Product" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>